.buildkit:
  image:
    name: moby/buildkit:rootless
    entrypoint: ["sh", "-c"]
  variables:
    BUILDKITD_FLAGS: --oci-worker-no-process-sandbox
  before_script:
    - |
      mkdir -p ~/.docker && cat > ~/.docker/config.json <<EOF
      {
        "auths": {
          "$CI_REGISTRY": {
            "auth": "$(echo -n "$CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD" | base64)"
          }
        }
      }
      EOF


stages:
  - build

build:
  extends: .buildkit
  stage: build
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - |
      buildctl-daemonless.sh build \
          --frontend=dockerfile.v0 \
          --local context=. \
          --local dockerfile=. \
          --output type=image,name=$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG,push=true
    - echo "Successfully built and pushed $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
